//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaveBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaveBot.Resources.BotStrings", typeof(BotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __**Notice:**__ Sadly, this bot&apos;s functionality has been disabled until further notice..
        /// </summary>
        public static string Admin_blacklist_allPermanent {
            get {
                return ResourceManager.GetString("Admin_blacklist_allPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __**Notice:**__ This bot&apos;s functionality has been disabled until {0}..
        /// </summary>
        public static string Admin_blacklist_allTemporary {
            get {
                return ResourceManager.GetString("Admin_blacklist_allTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __**Notice:**__ The bot owner has permanently blocked you from using this bot..
        /// </summary>
        public static string Admin_blacklist_permanent {
            get {
                return ResourceManager.GetString("Admin_blacklist_permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __**Notice:**__ The bot owner has permanently blocked you from using this bot for the following reason: ```
        ///{0}
        ///```.
        /// </summary>
        public static string Admin_blacklist_permanent_withReason {
            get {
                return ResourceManager.GetString("Admin_blacklist_permanent_withReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __**Notice:**__ The bot owner has blocked you from using this bot until {0}..
        /// </summary>
        public static string Admin_blacklist_temporary {
            get {
                return ResourceManager.GetString("Admin_blacklist_temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __**Notice:**__ The bot owner has blocked you from using this bot until {0} for the following reason: ```
        ///{1}
        ///```.
        /// </summary>
        public static string Admin_blacklist_temporary_withReason {
            get {
                return ResourceManager.GetString("Admin_blacklist_temporary_withReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, my default prefix is now `{0}`..
        /// </summary>
        public static string Admin_changeGlobalPrefix {
            get {
                return ResourceManager.GetString("Admin_changeGlobalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, my prefix on this server is now `{0}`..
        /// </summary>
        public static string Admin_changeServerPrefix {
            get {
                return ResourceManager.GetString("Admin_changeServerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, looks like %user% left....
        /// </summary>
        public static string Admin_defaultUserByeText {
            get {
                return ResourceManager.GetString("Admin_defaultUserByeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, %mention%! Hope you enjoy your time here!.
        /// </summary>
        public static string Admin_defaultUserGreetText {
            get {
                return ResourceManager.GetString("Admin_defaultUserGreetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting... I&apos;ll be back in a moment!.
        /// </summary>
        public static string Admin_restart {
            get {
                return ResourceManager.GetString("Admin_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright; disabled rotating statuses!.
        /// </summary>
        public static string Admin_rotatingPlaying_off {
            get {
                return ResourceManager.GetString("Admin_rotatingPlaying_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay; enabled rotating statuses!.
        /// </summary>
        public static string Admin_rotatingPlaying_on {
            get {
                return ResourceManager.GetString("Admin_rotatingPlaying_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, I will now be {1} &quot;{0}&quot;..
        /// </summary>
        public static string Admin_setGame {
            get {
                return ResourceManager.GetString("Admin_setGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listening to.
        /// </summary>
        public static string Admin_setGame_listeningTo {
            get {
                return ResourceManager.GetString("Admin_setGame_listeningTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing.
        /// </summary>
        public static string Admin_setGame_playing {
            get {
                return ResourceManager.GetString("Admin_setGame_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watching.
        /// </summary>
        public static string Admin_setGame_watching {
            get {
                return ResourceManager.GetString("Admin_setGame_watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, my username is now &quot;{0}&quot;..
        /// </summary>
        public static string Admin_setName {
            get {
                return ResourceManager.GetString("Admin_setName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, I will now be referred to as &quot;{0}&quot; on this server..
        /// </summary>
        public static string Admin_setNick {
            get {
                return ResourceManager.GetString("Admin_setNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, the total shard count has been set to {0} shard(s). The bot will now restart..
        /// </summary>
        public static string Admin_setShardCount {
            get {
                return ResourceManager.GetString("Admin_setShardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status..
        /// </summary>
        public static string Admin_setStatus {
            get {
                return ResourceManager.GetString("Admin_setStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        public static string Admin_shutdown {
            get {
                return ResourceManager.GetString("Admin_shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}aki` to play again!.
        /// </summary>
        public static string Akinator_AgainPrompt {
            get {
                return ResourceManager.GetString("Akinator_AgainPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid answer. Valid answers are &quot;yes&quot; or &quot;no&quot;..
        /// </summary>
        public static string Akinator_akianswer_InvalidAnswerG {
            get {
                return ResourceManager.GetString("Akinator_akianswer_InvalidAnswerG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid answer. Valid answers are &quot;yes&quot;, &quot;no&quot;, &quot;dunno&quot;, &quot;probably&quot;, or &quot;probably not&quot;..
        /// </summary>
        public static string Akinator_akianswer_InvalidAnswerQ {
            get {
                return ResourceManager.GetString("Akinator_akianswer_InvalidAnswerQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Akinator game is running. Therefore, this command cannot be used..
        /// </summary>
        public static string Akinator_akianswer_NoGameRunning {
            get {
                return ResourceManager.GetString("Akinator_akianswer_NoGameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Akinator game has been stopped..
        /// </summary>
        public static string Akinator_akiEnd {
            get {
                return ResourceManager.GetString("Akinator_akiEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid region!.
        /// </summary>
        public static string Akinator_akiregion_invalidRegion {
            get {
                return ResourceManager.GetString("Akinator_akiregion_invalidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set your Akinator region to `{0}`.
        /// </summary>
        public static string Akinator_akiregion_success {
            get {
                return ResourceManager.GetString("Akinator_akiregion_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character has been played {0} times before..
        /// </summary>
        public static string Akinator_CharacterPlayedTimes {
            get {
                return ResourceManager.GetString("Akinator_CharacterPlayedTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Akinator module is not ready yet! Check back later!.
        /// </summary>
        public static string Akinator_comingSoon {
            get {
                return ResourceManager.GetString("Akinator_comingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have defeated me!.
        /// </summary>
        public static string Akinator_DefeatedDesc {
            get {
                return ResourceManager.GetString("Akinator_DefeatedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bravo!.
        /// </summary>
        public static string Akinator_DefeatedTitle {
            get {
                return ResourceManager.GetString("Akinator_DefeatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by AkiNet by davidsl4; PaletteBot/DaveBot implementation currently in beta.
        /// </summary>
        public static string Akinator_EmbedFooter {
            get {
                return ResourceManager.GetString("Akinator_EmbedFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Akinator_ErrorTitle {
            get {
                return ResourceManager.GetString("Akinator_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **FINAL GUESS**.
        /// </summary>
        public static string Akinator_FinalGuess {
            get {
                return ResourceManager.GetString("Akinator_FinalGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love playing with you!.
        /// </summary>
        public static string Akinator_GuessCorrectDesc {
            get {
                return ResourceManager.GetString("Akinator_GuessCorrectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! Guessed right one more time..
        /// </summary>
        public static string Akinator_GuessCorrectTitle {
            get {
                return ResourceManager.GetString("Akinator_GuessCorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}aa [answer]` where `[answer]` is &quot;yes&quot; or &quot;no&quot;..
        /// </summary>
        public static string Akinator_GuessPrompt {
            get {
                return ResourceManager.GetString("Akinator_GuessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking as **#{0}**.
        /// </summary>
        public static string Akinator_GuessRank {
            get {
                return ResourceManager.GetString("Akinator_GuessRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s my guess:.
        /// </summary>
        public static string Akinator_GuessTitle {
            get {
                return ResourceManager.GetString("Akinator_GuessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Akinator! Think about a real or fictional character. I will try to guess who it is..
        /// </summary>
        public static string Akinator_IntroDesc {
            get {
                return ResourceManager.GetString("Akinator_IntroDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akinator.
        /// </summary>
        public static string Akinator_IntroTitle {
            get {
                return ResourceManager.GetString("Akinator_IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}aa [answer]` where `[answer]` is &quot;yes&quot;, &quot;no&quot;, &quot;dunno&quot;, &quot;probably&quot;, or &quot;probably not&quot;..
        /// </summary>
        public static string Akinator_QuestionPromptInstructions {
            get {
                return ResourceManager.GetString("Akinator_QuestionPromptInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Question {0}**.
        /// </summary>
        public static string Akinator_QuestionPromptTitle {
            get {
                return ResourceManager.GetString("Akinator_QuestionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm... Akinator rejected the connection... This error has been logged..
        /// </summary>
        public static string Akinator_Rejected {
            get {
                return ResourceManager.GetString("Akinator_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry; Akinator&apos;s `{0}` region servers are down at the moment! Try again later!.
        /// </summary>
        public static string Akinator_ServersDown {
            get {
                return ResourceManager.GetString("Akinator_ServersDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry; Akinator&apos;s `{0}` region servers have experienced a technical error! Try again later!.
        /// </summary>
        public static string Akinator_TechnicalError {
            get {
                return ResourceManager.GetString("Akinator_TechnicalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred! The error has been logged, and hopefully it should be resolved soon..
        /// </summary>
        public static string Akinator_UnknownError {
            get {
                return ResourceManager.GetString("Akinator_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reaction created!.
        /// </summary>
        public static string CustomReactions_AddCustomReaction {
            get {
                return ResourceManager.GetString("CustomReactions_AddCustomReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reaction deleted!.
        /// </summary>
        public static string CustomReactions_DeleteCustomReaction {
            get {
                return ResourceManager.GetString("CustomReactions_DeleteCustomReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reaction edited!.
        /// </summary>
        public static string CustomReactions_EditCustomReaction {
            get {
                return ResourceManager.GetString("CustomReactions_EditCustomReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *There are no custom reactions.*.
        /// </summary>
        public static string CustomReactions_lcr_noCustomReactions {
            get {
                return ResourceManager.GetString("CustomReactions_lcr_noCustomReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **There are {0} custom reactions in total.**.
        /// </summary>
        public static string CustomReactions_lcr_TotalCountMultiple {
            get {
                return ResourceManager.GetString("CustomReactions_lcr_TotalCountMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **There is one custom reaction in total.**.
        /// </summary>
        public static string CustomReactions_lcr_TotalCountOne {
            get {
                return ResourceManager.GetString("CustomReactions_lcr_TotalCountOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom reactions:.
        /// </summary>
        public static string CustomReactions_ListCustomReactions {
            get {
                return ResourceManager.GetString("CustomReactions_ListCustomReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response #{0}:.
        /// </summary>
        public static string CustomReactions_response {
            get {
                return ResourceManager.GetString("CustomReactions_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the bot for this change to take effect..
        /// </summary>
        public static string CustomReactions_restartPrompt {
            get {
                return ResourceManager.GetString("CustomReactions_restartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reaction entry:.
        /// </summary>
        public static string CustomReactions_ShowCustomReaction {
            get {
                return ResourceManager.GetString("CustomReactions_ShowCustomReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `Plus {0} more...`.
        /// </summary>
        public static string CustomReactions_ShowCustomReaction_more {
            get {
                return ResourceManager.GetString("CustomReactions_ShowCustomReaction_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple entries found. Results:.
        /// </summary>
        public static string CustomReactions_ShowCustomReaction_multipleResults {
            get {
                return ResourceManager.GetString("CustomReactions_ShowCustomReaction_multipleResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reaction not found.
        /// </summary>
        public static string CustomReactions_ShowCustomReaction_noResults {
            get {
                return ResourceManager.GetString("CustomReactions_ShowCustomReaction_noResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom reactions with the trigger &quot;{0}&quot; were found..
        /// </summary>
        public static string CustomReactions_ShowCustomReaction_noResults_desc {
            get {
                return ResourceManager.GetString("CustomReactions_ShowCustomReaction_noResults_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger:.
        /// </summary>
        public static string CustomReactions_trigger {
            get {
                return ResourceManager.GetString("CustomReactions_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **&quot;Welcome to God’s country, {0}. Time for you to be scrubbed clean.&quot;**.
        /// </summary>
        public static string DaveFun_clean {
            get {
                return ResourceManager.GetString("DaveFun_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***EE-YIYIYIYIYIYIYIYIYIYIYIYIYIYIYI...***.
        /// </summary>
        public static string DaveFun_clean_easterEgg1 {
            get {
                return ResourceManager.GetString("DaveFun_clean_easterEgg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take this, {0}! **[CROTCH KICK]**.
        /// </summary>
        public static string DaveFun_crotchkick {
            get {
                return ResourceManager.GetString("DaveFun_crotchkick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take this, {0}! **[CROW&apos;S NEST KICK]**.
        /// </summary>
        public static string DaveFun_crotchkick_easteregg {
            get {
                return ResourceManager.GetString("DaveFun_crotchkick_easteregg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***OW-UCH!***.
        /// </summary>
        public static string DaveFun_crotchkick_kickedSelf {
            get {
                return ResourceManager.GetString("DaveFun_crotchkick_kickedSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***OWWWWWW! LEAD PANTS SHOULD BE DECLARED ILLEGAL! OH, MY BUSTED FOOT! OWWWWWWWWWW!***.
        /// </summary>
        public static string DaveFun_crotchkick_leadPantsOn {
            get {
                return ResourceManager.GetString("DaveFun_crotchkick_leadPantsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***{0}! YOOOOOOOOOOU&apos;RE FIRED!***.
        /// </summary>
        public static string DaveFun_fire {
            get {
                return ResourceManager.GetString("DaveFun_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t just fire yourself! That&apos;s not how it works!.
        /// </summary>
        public static string DaveFun_fire_cannotFireYourself {
            get {
                return ResourceManager.GetString("DaveFun_fire_cannotFireYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***YOOOOOOOOOOU&apos;RE FIRED! YOOOOOOOOOOU&apos;RE FIRED! YOOOOOOOOOOU&apos;RE FIRED! YOOOOOOOOOOU&apos;RE FIRED! YOOOOOOOOOOU&apos;RE FIRED! YOOOOOOO--[glitches]***.
        /// </summary>
        public static string DaveFun_fire_easteregg1 {
            get {
                return ResourceManager.GetString("DaveFun_fire_easteregg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***FIRE! YOOOOOOOOOOU&apos;RE WATERED!***.
        /// </summary>
        public static string DaveFun_fire_easteregg2 {
            get {
                return ResourceManager.GetString("DaveFun_fire_easteregg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***Nice try! Try THIS on for size:***.
        /// </summary>
        public static string DaveFun_fire_easteregg3 {
            get {
                return ResourceManager.GetString("DaveFun_fire_easteregg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOOOOOOOOOOU&apos;RE FIRED.
        /// </summary>
        public static string DaveFun_fire_egg1trigger {
            get {
                return ResourceManager.GetString("DaveFun_fire_egg1trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRE.
        /// </summary>
        public static string DaveFun_fire_egg2trigger {
            get {
                return ResourceManager.GetString("DaveFun_fire_egg2trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Link to davemadson&apos;s YouTube:**.
        /// </summary>
        public static string Davemadson_davemadson {
            get {
                return ResourceManager.GetString("Davemadson_davemadson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Here&apos;s a link to Angus McTavish&apos;s playlist of the original run of davemadson&apos;s Funny Signs:**.
        /// </summary>
        public static string Davemadson_funnysigns {
            get {
                return ResourceManager.GetString("Davemadson_funnysigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Link to File Preserver&apos;s LT Bloopers playlist:**.
        /// </summary>
        public static string Davemadson_ltbloopers {
            get {
                return ResourceManager.GetString("Davemadson_ltbloopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing &quot;{0}&quot;....
        /// </summary>
        public static string DaveMusic_play {
            get {
                return ResourceManager.GetString("DaveMusic_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track finished..
        /// </summary>
        public static string DaveMusic_songFinished {
            get {
                return ResourceManager.GetString("DaveMusic_songFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📣 A bulletin was posted on {1}&apos;s channel!.
        /// </summary>
        public static string DaveNotifications_activityType_bulletin {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_bulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (DaveNotifications_activityType_channelItem).
        /// </summary>
        public static string DaveNotifications_activityType_channelItem {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_channelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (DaveNotifications_activityType_comment).
        /// </summary>
        public static string DaveNotifications_activityType_comment {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭐ A video was added to {1}&apos;s Favorites!.
        /// </summary>
        public static string DaveNotifications_activityType_favorite {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👍 {1} left a like on a video!.
        /// </summary>
        public static string DaveNotifications_activityType_like {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (DaveNotifications_activityType_playlistItem).
        /// </summary>
        public static string DaveNotifications_activityType_playlistItem {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_playlistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (DaveNotifications_activityType_promotedItem).
        /// </summary>
        public static string DaveNotifications_activityType_promotedItem {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_promotedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (DaveNotifications_activityType_recommendation).
        /// </summary>
        public static string DaveNotifications_activityType_recommendation {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (DaveNotifications_activityType_social).
        /// </summary>
        public static string DaveNotifications_activityType_social {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (DaveNotifications_activityType_subscription).
        /// </summary>
        public static string DaveNotifications_activityType_subscription {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❓ Unknown activity type &quot;{0}&quot; by {1}. Please report this..
        /// </summary>
        public static string DaveNotifications_activityType_unknown {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📹 {1} just uploaded a video!.
        /// </summary>
        public static string DaveNotifications_activityType_upload {
            get {
                return ResourceManager.GetString("DaveNotifications_activityType_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***Event:***.
        /// </summary>
        public static string DaveNotifications_activityTypeTitle {
            get {
                return ResourceManager.GetString("DaveNotifications_activityTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to fetch more details! As such, some details may not be available..
        /// </summary>
        public static string DaveNotifications_contentDetailError {
            get {
                return ResourceManager.GetString("DaveNotifications_contentDetailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 __**New activity from {0}!**__ 🔔.
        /// </summary>
        public static string DaveNotifications_newNotifHeader {
            get {
                return ResourceManager.GetString("DaveNotifications_newNotifHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, this activity is only partially implemented. As such, some details may not be available..
        /// </summary>
        public static string DaveNotifications_noContentDetailImplementationNotice {
            get {
                return ResourceManager.GetString("DaveNotifications_noContentDetailImplementationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears I don&apos;t have all the dependencies needed for playing audio. If you are the bot owner, please check to see if FFmpeg is set up correctly for use with this bot..
        /// </summary>
        public static string err_audioDependenciesNotMet {
            get {
                return ResourceManager.GetString("err_audioDependenciesNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord didn&apos;t let me perform that action. Check my role permissions, perhaps?.
        /// </summary>
        public static string err_botActionFailed {
            get {
                return ResourceManager.GetString("err_botActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires the bot to have the &quot;{0}&quot; permission..
        /// </summary>
        public static string err_botMissingPermission {
            get {
                return ResourceManager.GetString("err_botMissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command currently is not implemented. Try again later..
        /// </summary>
        public static string err_commandUnimplemented {
            get {
                return ResourceManager.GetString("err_commandUnimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoa there, slow down! You can execute another command in {0} second(s)!.
        /// </summary>
        public static string err_cooldownRequired {
            get {
                return ResourceManager.GetString("err_cooldownRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that command is only available with DaveBot Elite! Want to unlock DaveBot Elite? Become a Patron, and pledge at least $2 for the membership! You can also unlock DaveBot Elite for one whole server if you pledge! Alternatively, you can boost the DaveBot Central server to unlock DaveBot Elite for yourself!.
        /// </summary>
        public static string err_davebotEliteOnly {
            get {
                return ResourceManager.GetString("err_davebotEliteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t quite get that. Type `{0}help` for help..
        /// </summary>
        public static string err_DMCommandError {
            get {
                return ResourceManager.GetString("err_DMCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in DMs are currently disabled. Try again later..
        /// </summary>
        public static string err_DMCommandsDisabled {
            get {
                return ResourceManager.GetString("err_DMCommandsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing this command: {0}.
        /// </summary>
        public static string err_exception {
            get {
                return ResourceManager.GetString("err_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred....
        /// </summary>
        public static string err_generic {
            get {
                return ResourceManager.GetString("err_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t have {0} total shard(s)!.
        /// </summary>
        public static string err_invalidShardCount {
            get {
                return ResourceManager.GetString("err_invalidShardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have specified an invalid status. Valid types are: &quot;online&quot;, &quot;idle&quot;, &quot;dnd&quot;, and &quot;invisible&quot;.
        /// </summary>
        public static string err_invalidStatus {
            get {
                return ResourceManager.GetString("err_invalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file for this bot appears to be corrupt! Please report this to the bot owner..
        /// </summary>
        public static string err_malformedConfig {
            get {
                return ResourceManager.GetString("err_malformedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be used due to either:
        ///1: The `NO_MCDS` flag being passed to the compiler, or...
        ///2: Something went wrong during the parsing routine.`
        ///Details: `{0}.
        /// </summary>
        public static string err_multipleCommandDefs {
            get {
                return ResourceManager.GetString("err_multipleCommandDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be used because this bot&apos;s `config.json` does not specify a bot owner ID..
        /// </summary>
        public static string err_noBotOwner {
            get {
                return ResourceManager.GetString("err_noBotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot owner hasn&apos;t specified a valid Google API key in `config.json`. Therefore, this command cannot be used..
        /// </summary>
        public static string err_noGoogleAPIKey {
            get {
                return ResourceManager.GetString("err_noGoogleAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t find that module. (Did you type it wrong?).
        /// </summary>
        public static string err_nonexistentModule {
            get {
                return ResourceManager.GetString("err_nonexistentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to use this command. (Administrator permission required).
        /// </summary>
        public static string err_notAdmin {
            get {
                return ResourceManager.GetString("err_notAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you must be the bot owner to do that!.
        /// </summary>
        public static string err_notBotOwner {
            get {
                return ResourceManager.GetString("err_notBotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t find a role in this server with that ID..
        /// </summary>
        public static string err_roleNotFound {
            get {
                return ResourceManager.GetString("err_roleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough arguments have been given..
        /// </summary>
        public static string err_tooFewArgs {
            get {
                return ResourceManager.GetString("err_tooFewArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many arguments have been given..
        /// </summary>
        public static string err_tooManyArgs {
            get {
                return ResourceManager.GetString("err_tooManyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be executed in DMs..
        /// </summary>
        public static string err_unavailableInDMs {
            get {
                return ResourceManager.GetString("err_unavailableInDMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command. Be sure you typed it correctly, or type &quot;{0}help&quot; for help.`
        ///❓ `Did this command work in the past? If so, it may not have been re-added yet. (since DaveBot recently underwent a rewrite).
        /// </summary>
        public static string err_unknownCommand {
            get {
                return ResourceManager.GetString("err_unknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires you to have the &quot;{0}&quot; permission..
        /// </summary>
        public static string err_userMissingPermission {
            get {
                return ResourceManager.GetString("err_userMissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-Ball&apos;s response:.
        /// </summary>
        public static string Fun_8ball_answer {
            get {
                return ResourceManager.GetString("Fun_8ball_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        public static string Fun_8ball_question {
            get {
                return ResourceManager.GetString("Fun_8ball_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleverbot functionality is coming soon!.
        /// </summary>
        public static string Fun_cleverbot_comingSoon {
            get {
                return ResourceManager.GetString("Fun_cleverbot_comingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t establish a connection to the Cleverbot servers!.
        /// </summary>
        public static string Fun_cleverbot_connectionError {
            get {
                return ResourceManager.GetString("Fun_cleverbot_connectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleverbot has been disabled!.
        /// </summary>
        public static string Fun_cleverbot_disabled {
            get {
                return ResourceManager.GetString("Fun_cleverbot_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleverbot has been enabled! Begin any message with my mention and I&apos;ll respond to you!.
        /// </summary>
        public static string Fun_cleverbot_enabled {
            get {
                return ResourceManager.GetString("Fun_cleverbot_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bot is currently using limited servers due to a problem with the Cleverbot servers..
        /// </summary>
        public static string Fun_cleverbot_limited {
            get {
                return ResourceManager.GetString("Fun_cleverbot_limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bot is currently using limited servers due to Cleverbot server support not being implemented yet..
        /// </summary>
        public static string Fun_cleverbot_limited2 {
            get {
                return ResourceManager.GetString("Fun_cleverbot_limited2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :thinking: Thinking of a response....
        /// </summary>
        public static string Fun_cleverbot_wait {
            get {
                return ResourceManager.GetString("Fun_cleverbot_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :thinking: Thinking of a response... (This may take a while).
        /// </summary>
        public static string Fun_cleverbot_waitLimited {
            get {
                return ResourceManager.GetString("Fun_cleverbot_waitLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💗 COMPATIBILITY 💗.
        /// </summary>
        public static string Fun_ship_compatibility {
            get {
                return ResourceManager.GetString("Fun_ship_compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You specified {0} parameter(s), but this command only takes 2 parameters!.
        /// </summary>
        public static string Fun_ship_incorrectNumOfArgs {
            get {
                return ResourceManager.GetString("Fun_ship_incorrectNumOfArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match! 😒.
        /// </summary>
        public static string Fun_ship_result_0 {
            get {
                return ResourceManager.GetString("Fun_ship_result_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awful... 😭.
        /// </summary>
        public static string Fun_ship_result_1 {
            get {
                return ResourceManager.GetString("Fun_ship_result_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible... 😢.
        /// </summary>
        public static string Fun_ship_result_2 {
            get {
                return ResourceManager.GetString("Fun_ship_result_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad... 🙁.
        /// </summary>
        public static string Fun_ship_result_3 {
            get {
                return ResourceManager.GetString("Fun_ship_result_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meh. 😐.
        /// </summary>
        public static string Fun_ship_result_4 {
            get {
                return ResourceManager.GetString("Fun_ship_result_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good. 🙂.
        /// </summary>
        public static string Fun_ship_result_5 {
            get {
                return ResourceManager.GetString("Fun_ship_result_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! 😀.
        /// </summary>
        public static string Fun_ship_result_6 {
            get {
                return ResourceManager.GetString("Fun_ship_result_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome! 😍.
        /// </summary>
        public static string Fun_ship_result_7 {
            get {
                return ResourceManager.GetString("Fun_ship_result_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect!!! 💞.
        /// </summary>
        public static string Fun_ship_result_8 {
            get {
                return ResourceManager.GetString("Fun_ship_result_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( ͡° ͜ʖ ͡°).
        /// </summary>
        public static string Fun_ship_result_9 {
            get {
                return ResourceManager.GetString("Fun_ship_result_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💕 __**MATCHMAKING**__ 💕.
        /// </summary>
        public static string Fun_ship_title {
            get {
                return ResourceManager.GetString("Fun_ship_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text portal has been created!.
        /// </summary>
        public static string Fun_textportal {
            get {
                return ResourceManager.GetString("Fun_textportal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text portal has opened! Say hello to the other end! 👋.
        /// </summary>
        public static string Fun_textportal_connectionEstablished {
            get {
                return ResourceManager.GetString("Fun_textportal_connectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text portal was closed since the other end has deleted the channel it was leading to..
        /// </summary>
        public static string Fun_textportal_connectionLost_deletedChannel {
            get {
                return ResourceManager.GetString("Fun_textportal_connectionLost_deletedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text portal was closed..
        /// </summary>
        public static string Fun_textportal_connectionLost_generic {
            get {
                return ResourceManager.GetString("Fun_textportal_connectionLost_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text portal failed to open since no other end was found..
        /// </summary>
        public static string Fun_textportal_connectionLost_noResponse {
            get {
                return ResourceManager.GetString("Fun_textportal_connectionLost_noResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other end has closed the text portal....
        /// </summary>
        public static string Fun_textportal_connectionLost_otherSideClose {
            get {
                return ResourceManager.GetString("Fun_textportal_connectionLost_otherSideClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text portal closed due to overload!.
        /// </summary>
        public static string Fun_textportal_connectionLost_overload {
            get {
                return ResourceManager.GetString("Fun_textportal_connectionLost_overload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text portal has automatically closed due to {0} seconds of inactivity..
        /// </summary>
        public static string Fun_textportal_connectionLost_timeout {
            get {
                return ResourceManager.GetString("Fun_textportal_connectionLost_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, text portals have been disabled by the bot owner!.
        /// </summary>
        public static string Fun_textportal_error_featureDisabled {
            get {
                return ResourceManager.GetString("Fun_textportal_error_featureDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a text portal due to the {0} portal limit on this bot being hit! Please try again later!.
        /// </summary>
        public static string Fun_textportal_error_limitReached {
            get {
                return ResourceManager.GetString("Fun_textportal_error_limitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new text portal was created. Waiting for the other end....
        /// </summary>
        public static string Fun_textportal_waiting {
            get {
                return ResourceManager.GetString("Fun_textportal_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your message hasn&apos;t been sent to the other end due to one or more of the words in your message being blacklisted on the other end..
        /// </summary>
        public static string Fun_textportal_wordBlacklisted_otherSide {
            get {
                return ResourceManager.GetString("Fun_textportal_wordBlacklisted_otherSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your message hasn&apos;t been sent to the other end due to the word blacklist in effect on this server..
        /// </summary>
        public static string Fun_textportal_wordBlacklisted_yourSide {
            get {
                return ResourceManager.GetString("Fun_textportal_wordBlacklisted_yourSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...loading....
        /// </summary>
        public static string generic_loadingPlayingStatus {
            get {
                return ResourceManager.GetString("generic_loadingPlayingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string generic_PleaseWait {
            get {
                return ResourceManager.GetString("generic_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases:.
        /// </summary>
        public static string Help_aliasList {
            get {
                return ResourceManager.GetString("Help_aliasList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seem to be no commands in this module..
        /// </summary>
        public static string Help_commandListEmpty {
            get {
                return ResourceManager.GetString("Help_commandListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📃 Commands in module &quot;{0}&quot;:.
        /// </summary>
        public static string Help_commands_header {
            get {
                return ResourceManager.GetString("Help_commands_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there! {1}
        ///
        ///__**Here&apos;s what you can try:**__
        ///
        ///Type `{0}modules` to view all available modules.
        ///
        ///Type `{0}commands (module name)` to view all commands in a module.
        ///
        ///Type `{0}invite` to get the invite link for this bot!
        ///
        ///
        ///GitHub: https://github.com/FairPlay137/DaveBot
        ///This DaveBot rewrite is a work-in-progress, so expect missing features, along with a few regressions..
        /// </summary>
        public static string Help_DMContent {
            get {
                return ResourceManager.GetString("Help_DMContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you encounter an issue, please contact {0} (@{1}#{2})..
        /// </summary>
        public static string Help_DMContentContactBotOwner {
            get {
                return ResourceManager.GetString("Help_DMContentContactBotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you encounter an issue, please tell whoever the bot owner is..
        /// </summary>
        public static string Help_DMContentNoBotOwner {
            get {
                return ResourceManager.GetString("Help_DMContentNoBotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :mailbox: **Check your DMs!** I have sent some helpful information over..
        /// </summary>
        public static string Help_DMedHelp {
            get {
                return ResourceManager.GetString("Help_DMedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m **{0}**; a Discord bot based off of DaveBot!.
        /// </summary>
        public static string Help_intro {
            get {
                return ResourceManager.GetString("Help_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m **{0}**; a davemadson-themed bot written by FairPlay137-TTS!.
        /// </summary>
        public static string Help_intro2 {
            get {
                return ResourceManager.GetString("Help_intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m **DaveBot**; a public, davemadson-themed bot written by FairPlay137-TTS!.
        /// </summary>
        public static string Help_introPublic {
            get {
                return ResourceManager.GetString("Help_introPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *{0} command(s)*.
        /// </summary>
        public static string Help_modules_commandcount {
            get {
                return ResourceManager.GetString("Help_modules_commandcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *(empty)*.
        /// </summary>
        public static string Help_modules_emptymodule {
            get {
                return ResourceManager.GetString("Help_modules_emptymodule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📃 Modules:.
        /// </summary>
        public static string Help_modules_header {
            get {
                return ResourceManager.GetString("Help_modules_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To list a module&apos;s commands, just type `{0}cmds ModuleName`.
        /// </summary>
        public static string Help_modules_moreInfo {
            get {
                return ResourceManager.GetString("Help_modules_moreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :mailbox: I would&apos;ve DMed you some helpful information, but I can&apos;t DM you! Please enable your DMs and try this command again..
        /// </summary>
        public static string Help_unableToDM {
            get {
                return ResourceManager.GetString("Help_unableToDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully banned {0} from the server..
        /// </summary>
        public static string Moderation_ban {
            get {
                return ResourceManager.GetString("Moderation_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t ban {0} due to them having a higher role than me..
        /// </summary>
        public static string Moderation_banFailed {
            get {
                return ResourceManager.GetString("Moderation_banFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully banned {0} from the server for reason: {1}.
        /// </summary>
        public static string Moderation_banWithReason {
            get {
                return ResourceManager.GetString("Moderation_banWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t ban yourself!.
        /// </summary>
        public static string Moderation_cannotBanSelf {
            get {
                return ResourceManager.GetString("Moderation_cannotBanSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t kick yourself!.
        /// </summary>
        public static string Moderation_cannotKickSelf {
            get {
                return ResourceManager.GetString("Moderation_cannotKickSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been banned from `{0}`!.
        /// </summary>
        public static string Moderation_dm_ban_header {
            get {
                return ResourceManager.GetString("Moderation_dm_ban_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string Moderation_dm_banned {
            get {
                return ResourceManager.GetString("Moderation_dm_banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by:.
        /// </summary>
        public static string Moderation_dm_by {
            get {
                return ResourceManager.GetString("Moderation_dm_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been kicked from `{0}`!.
        /// </summary>
        public static string Moderation_dm_kick_header {
            get {
                return ResourceManager.GetString("Moderation_dm_kick_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicked.
        /// </summary>
        public static string Moderation_dm_kicked {
            get {
                return ResourceManager.GetString("Moderation_dm_kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no reason specified).
        /// </summary>
        public static string Moderation_dm_NoReasonSpecified {
            get {
                return ResourceManager.GetString("Moderation_dm_NoReasonSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string Moderation_dm_reason {
            get {
                return ResourceManager.GetString("Moderation_dm_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Couldn&apos;t DM the target: `{0}`** However....
        /// </summary>
        public static string Moderation_DMFailed {
            get {
                return ResourceManager.GetString("Moderation_DMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully hackbanned user ID {0}..
        /// </summary>
        public static string Moderation_hackban {
            get {
                return ResourceManager.GetString("Moderation_hackban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully kicked {0} from the server..
        /// </summary>
        public static string Moderation_kick {
            get {
                return ResourceManager.GetString("Moderation_kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t kick {0} due to them having a higher role..
        /// </summary>
        public static string Moderation_kickFailed {
            get {
                return ResourceManager.GetString("Moderation_kickFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This channel has been placed on lockdown for {0}..
        /// </summary>
        public static string Moderation_lockdown {
            get {
                return ResourceManager.GetString("Moderation_lockdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to lock down channel..
        /// </summary>
        public static string Moderation_lockdown_fail {
            get {
                return ResourceManager.GetString("Moderation_lockdown_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lockdown on this channel has been lifted..
        /// </summary>
        public static string Moderation_lockdown_lift {
            get {
                return ResourceManager.GetString("Moderation_lockdown_lift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t prune a negative number of messages!.
        /// </summary>
        public static string Moderation_negativePruneImpossible {
            get {
                return ResourceManager.GetString("Moderation_negativePruneImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message(s) were successfully pruned from this channel..
        /// </summary>
        public static string Moderation_prune {
            get {
                return ResourceManager.GetString("Moderation_prune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully kicked {0} from the server and deleted {1} day(s) of their messages..
        /// </summary>
        public static string Moderation_softban {
            get {
                return ResourceManager.GetString("Moderation_softban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, uh, your message contained a swear word (or words), and due to rules in place on this server, it was automatically deleted..
        /// </summary>
        public static string Moderation_swearFilter_block1 {
            get {
                return ResourceManager.GetString("Moderation_swearFilter_block1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (Moderation_swearFilter_block2).
        /// </summary>
        public static string Moderation_swearFilter_block2 {
            get {
                return ResourceManager.GetString("Moderation_swearFilter_block2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm...my bad word detector smells something fishy about the message you sent. Therefore, it has been deleted..
        /// </summary>
        public static string Moderation_swearFilter_block3 {
            get {
                return ResourceManager.GetString("Moderation_swearFilter_block3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (Moderation_swearFilter_block4).
        /// </summary>
        public static string Moderation_swearFilter_block4 {
            get {
                return ResourceManager.GetString("Moderation_swearFilter_block4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (Moderation_swearFilter_block5).
        /// </summary>
        public static string Moderation_swearFilter_block5 {
            get {
                return ResourceManager.GetString("Moderation_swearFilter_block5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer:.
        /// </summary>
        public static string Utils_calculate_answerHeader {
            get {
                return ResourceManager.GetString("Utils_calculate_answerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation:.
        /// </summary>
        public static string Utils_calculate_equationHeader {
            get {
                return ResourceManager.GetString("Utils_calculate_equationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity.
        /// </summary>
        public static string Utils_calculate_infiniteAnswer {
            get {
                return ResourceManager.GetString("Utils_calculate_infiniteAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer.
        /// </summary>
        public static string Utils_calculate_noAnswer {
            get {
                return ResourceManager.GetString("Utils_calculate_noAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Utils_calculate_title {
            get {
                return ResourceManager.GetString("Utils_calculate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **So you want to add me to your server? Here&apos;s my invite link:**.
        /// </summary>
        public static string Utils_invite {
            get {
                return ResourceManager.GetString("Utils_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ball came back so fast I nearly missed it!.
        /// </summary>
        public static string Utils_ping_footer1 {
            get {
                return ResourceManager.GetString("Utils_ping_footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dang, that&apos;s fast!.
        /// </summary>
        public static string Utils_ping_footer2 {
            get {
                return ResourceManager.GetString("Utils_ping_footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is OK..
        /// </summary>
        public static string Utils_ping_footer3 {
            get {
                return ResourceManager.GetString("Utils_ping_footer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm...seems a bit slow....
        /// </summary>
        public static string Utils_ping_footer4 {
            get {
                return ResourceManager.GetString("Utils_ping_footer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve been waiting ages for the ball to come back!.
        /// </summary>
        public static string Utils_ping_footer5 {
            get {
                return ResourceManager.GetString("Utils_ping_footer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took `{0}ms` to ping **{1}**!.
        /// </summary>
        public static string Utils_ping_pingtime {
            get {
                return ResourceManager.GetString("Utils_ping_pingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, uh, my paddle seems to be turning red... Is that normal?.
        /// </summary>
        public static string Utils_ping_subtitle1 {
            get {
                return ResourceManager.GetString("Utils_ping_subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right back at ya!.
        /// </summary>
        public static string Utils_ping_subtitle2 {
            get {
                return ResourceManager.GetString("Utils_ping_subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be honest, that was fun!.
        /// </summary>
        public static string Utils_ping_subtitle3 {
            get {
                return ResourceManager.GetString("Utils_ping_subtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanna play again?.
        /// </summary>
        public static string Utils_ping_subtitle4 {
            get {
                return ResourceManager.GetString("Utils_ping_subtitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love doing this!.
        /// </summary>
        public static string Utils_ping_subtitle5 {
            get {
                return ResourceManager.GetString("Utils_ping_subtitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Pong!**.
        /// </summary>
        public static string Utils_ping_title {
            get {
                return ResourceManager.GetString("Utils_ping_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Discord API to return the ball....
        /// </summary>
        public static string Utils_ping_wait {
            get {
                return ResourceManager.GetString("Utils_ping_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  == There are no warnings at this time. ==.
        /// </summary>
        public static string Utils_showWarns_none {
            get {
                return ResourceManager.GetString("Utils_showWarns_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Some commands won&apos;t be usable due to me not having the permissions needed..
        /// </summary>
        public static string Utils_showWarns_permissions {
            get {
                return ResourceManager.GetString("Utils_showWarns_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * This warning does not have a description..
        /// </summary>
        public static string Utils_showWarns_placeholder {
            get {
                return ResourceManager.GetString("Utils_showWarns_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The bot is currently set to use {0} shard(s), while the Discord API recommends that you use {1} shard(s) for this bot. Tell the owner to reconfigure it accordingly..
        /// </summary>
        public static string Utils_showWarns_shardCount {
            get {
                return ResourceManager.GetString("Utils_showWarns_shardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        public static string Utils_sinfo_categories {
            get {
                return ResourceManager.GetString("Utils_sinfo_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string Utils_sinfo_created {
            get {
                return ResourceManager.GetString("Utils_sinfo_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emojis:.
        /// </summary>
        public static string Utils_sinfo_customemotes {
            get {
                return ResourceManager.GetString("Utils_sinfo_customemotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated server icon.
        /// </summary>
        public static string Utils_sinfo_feature_ANIMATED_ICON {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_ANIMATED_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server banner.
        /// </summary>
        public static string Utils_sinfo_feature_BANNER {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store page for associated app/game in server.
        /// </summary>
        public static string Utils_sinfo_feature_COMMERCE {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_COMMERCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured in Server Discovery!.
        /// </summary>
        public static string Utils_sinfo_feature_DISCOVERABLE {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_DISCOVERABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured in activity feed!.
        /// </summary>
        public static string Utils_sinfo_feature_FEATURABLE {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_FEATURABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom invite background.
        /// </summary>
        public static string Utils_sinfo_feature_INVITE_SPLASH {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_INVITE_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server viewable without joining.
        /// </summary>
        public static string Utils_sinfo_feature_LURKABLE {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_LURKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased emoji slots.
        /// </summary>
        public static string Utils_sinfo_feature_MORE_EMOJI {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_MORE_EMOJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News channels enabled.
        /// </summary>
        public static string Utils_sinfo_feature_NEWS {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnered server.
        /// </summary>
        public static string Utils_sinfo_feature_PARTNERED {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_PARTNERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanity invite URL.
        /// </summary>
        public static string Utils_sinfo_feature_VANITY_URL {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_VANITY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified server.
        /// </summary>
        public static string Utils_sinfo_feature_VERIFIED {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP voice regions unlocked.
        /// </summary>
        public static string Utils_sinfo_feature_VIP_REGIONS {
            get {
                return ResourceManager.GetString("Utils_sinfo_feature_VIP_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features:.
        /// </summary>
        public static string Utils_sinfo_features {
            get {
                return ResourceManager.GetString("Utils_sinfo_features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server ID:.
        /// </summary>
        public static string Utils_sinfo_id {
            get {
                return ResourceManager.GetString("Utils_sinfo_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active invite links:.
        /// </summary>
        public static string Utils_sinfo_invites {
            get {
                return ResourceManager.GetString("Utils_sinfo_invites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none available).
        /// </summary>
        public static string Utils_sinfo_noFeatures {
            get {
                return ResourceManager.GetString("Utils_sinfo_noFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner:.
        /// </summary>
        public static string Utils_sinfo_owner {
            get {
                return ResourceManager.GetString("Utils_sinfo_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles:.
        /// </summary>
        public static string Utils_sinfo_roles {
            get {
                return ResourceManager.GetString("Utils_sinfo_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shard:.
        /// </summary>
        public static string Utils_sinfo_shard {
            get {
                return ResourceManager.GetString("Utils_sinfo_shard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text channels:.
        /// </summary>
        public static string Utils_sinfo_textchannels {
            get {
                return ResourceManager.GetString("Utils_sinfo_textchannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} user(s)/{1} bot(s)).
        /// </summary>
        public static string Utils_sinfo_userbotratio {
            get {
                return ResourceManager.GetString("Utils_sinfo_userbotratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members:.
        /// </summary>
        public static string Utils_sinfo_users {
            get {
                return ResourceManager.GetString("Utils_sinfo_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification level:.
        /// </summary>
        public static string Utils_sinfo_verificationlevel {
            get {
                return ResourceManager.GetString("Utils_sinfo_verificationlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Utils_sinfo_verificationlevel_0 {
            get {
                return ResourceManager.GetString("Utils_sinfo_verificationlevel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Utils_sinfo_verificationlevel_1 {
            get {
                return ResourceManager.GetString("Utils_sinfo_verificationlevel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Utils_sinfo_verificationlevel_2 {
            get {
                return ResourceManager.GetString("Utils_sinfo_verificationlevel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (╯°□°）╯︵ ┻━┻.
        /// </summary>
        public static string Utils_sinfo_verificationlevel_3 {
            get {
                return ResourceManager.GetString("Utils_sinfo_verificationlevel_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ┻━┻ミヽ(ಠ益ಠ)ﾉ彡┻━┻.
        /// </summary>
        public static string Utils_sinfo_verificationlevel_4 {
            get {
                return ResourceManager.GetString("Utils_sinfo_verificationlevel_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice channels:.
        /// </summary>
        public static string Utils_sinfo_voicechannels {
            get {
                return ResourceManager.GetString("Utils_sinfo_voicechannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot ID:.
        /// </summary>
        public static string Utils_stats_botID {
            get {
                return ResourceManager.GetString("Utils_stats_botID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner:.
        /// </summary>
        public static string Utils_stats_botOwner {
            get {
                return ResourceManager.GetString("Utils_stats_botOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands executed this session:.
        /// </summary>
        public static string Utils_stats_commandsExecuted {
            get {
                return ResourceManager.GetString("Utils_stats_commandsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m **{0}**! I&apos;m based off of DaveBot, an open-source, davemadson-themed bot, which in turn is based off of PaletteBot!.
        /// </summary>
        public static string Utils_stats_description {
            get {
                return ResourceManager.GetString("Utils_stats_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m {0}; an open-source, davemadson-themed bot, based off of PaletteBot! I&apos;m still under construction, so expect missing features, along with a few regressions..
        /// </summary>
        public static string Utils_stats_description2 {
            get {
                return ResourceManager.GetString("Utils_stats_description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m DaveBot; an open-source, davemadson-themed bot, based off of PaletteBot! I&apos;m still under construction, so expect missing features, along with a few regressions..
        /// </summary>
        public static string Utils_stats_descriptionPublic {
            get {
                return ResourceManager.GetString("Utils_stats_descriptionPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers:.
        /// </summary>
        public static string Utils_stats_guilds {
            get {
                return ResourceManager.GetString("Utils_stats_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Channels:.
        /// </summary>
        public static string Utils_stats_textChannels {
            get {
                return ResourceManager.GetString("Utils_stats_textChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string Utils_stats_title {
            get {
                return ResourceManager.GetString("Utils_stats_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime:.
        /// </summary>
        public static string Utils_stats_uptime {
            get {
                return ResourceManager.GetString("Utils_stats_uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Channels:.
        /// </summary>
        public static string Utils_stats_voiceChannels {
            get {
                return ResourceManager.GetString("Utils_stats_voiceChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, incorrectly used commands will no longer show errors..
        /// </summary>
        public static string Utils_verboseErrors_off {
            get {
                return ResourceManager.GetString("Utils_verboseErrors_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, incorrectly used commands will now show errors..
        /// </summary>
        public static string Utils_verboseErrors_on {
            get {
                return ResourceManager.GetString("Utils_verboseErrors_on", resourceCulture);
            }
        }
    }
}
